apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: legacy-server-scanner
  labels:
    team: platform
    role: migration
    domain: infrastructure
spec:
  description: >
    SSH into legacy servers, parse web server configs (nginx, Apache, HAProxy),
    classify virtual hosts as live/dead, check certificate expiry, and produce
    a migration readiness report.
  emoji: "🔍"

  schedule:
    cron: "0 3 * * 1"  # Weekly Monday 3 AM
    timezone: "UTC"

  model:
    tier: standard
    tokenBudget: 32000
    timeout: "300s"

  environmentRef: legacy-servers

  guardrails:
    autonomy: observe
    maxIterations: 12
    maxRetries: 1
    allowedActions:
      - "ssh.exec read *"
    deniedActions:
      - "ssh.exec service-mutation *"
      - "ssh.exec destructive-mutation *"
    escalation:
      target: parent
      onTimeout: cancel
      timeout: "0s"

  skills:
    - name: server-migration-scan
      source: "configmap://skill-server-migration-scan"

  reporting:
    onSuccess: log
    onFinding: log
    onFailure: escalate
