apiVersion: legator.io/v1alpha1
kind: LegatorAgent
metadata:
  name: log-rotation-auditor
  labels:
    team: ops
    role: hygiene
    domain: infrastructure
spec:
  description: >
    SSH into servers, inspect logrotate configuration, find logs exceeding
    size thresholds, check disk pressure, and report servers at risk of
    disk exhaustion.
  emoji: "📋"

  schedule:
    cron: "0 2 * * *"  # Daily 2 AM
    timezone: "UTC"

  model:
    tier: fast
    tokenBudget: 12000
    timeout: "120s"

  environmentRef: server-fleet

  guardrails:
    autonomy: observe
    maxIterations: 8
    maxRetries: 1
    allowedActions:
      - "ssh.exec read *"
    deniedActions:
      - "ssh.exec service-mutation *"
      - "ssh.exec destructive-mutation *"
    escalation:
      target: parent
      onTimeout: cancel
      timeout: "0s"

  skills:
    - name: log-rotation-audit
      source: "configmap://skill-log-rotation-audit"

  reporting:
    onSuccess: silent
    onFinding: log
    onFailure: escalate
