apiVersion: core.infraagent.io/v1alpha1
kind: InfraAgent
metadata:
  name: vigil
  namespace: agents
  labels:
    team: platform
    role: testing
spec:
  description: "E2E regression suite — runs full platform test battery daily at 5 AM."
  emoji: "🔥"
  schedule:
    cron: "0 5 * * *"
    timezone: "UTC"
  model:
    tier: standard
    tokenBudget: 50000
    timeout: "1800s"
  skills:
    - name: e2e-regression
      source: bundled
  capabilities:
    required:
      - http
      - kubectl.read
  guardrails:
    autonomy: observe
    allowedActions:
      - "http.get *"
      - "http.post *"
      - "kubectl.get *"
      - "kubectl.describe *"
      - "kubectl.logs *"
    deniedActions:
      - "kubectl.delete *"
      - "kubectl.scale *"
    maxIterations: 50
    maxRetries: 1
  reporting:
    onSuccess: log
    onFailure: escalate
    onFinding: notify
  environmentRef: dev-lab
