apiVersion: core.infraagent.io/v1alpha1
kind: AgentEnvironment
metadata:
  name: dev-lab
  namespace: agents
  labels:
    tier: development
spec:
  connection:
    kind: in-cluster
  endpoints:
    platform:
      url: https://platform.example.com
      healthPath: /healthcheck
    grafana:
      url: https://grafana.example.com
      healthPath: /api/health
    argocd:
      url: https://argocd.example.com
      healthPath: /healthz
    harbor:
      url: https://harbor.example.com
      healthPath: /api/v2.0/health
    alertmanager:
      url: http://alertmanager.monitoring:9093
      healthPath: /-/healthy
      internal: true
    backstage:
      url: https://backstage.example.com
      healthPath: /healthcheck
  namespaces:
    monitoring:
      - monitoring
    apps:
      - backstage
      - ideavault
    system:
      - kube-system
      - cert-manager
      - argocd
      - kargo
  credentials:
    github:
      secretRef: github-pat
      type: token
  channels:
    oncall:
      type: telegram
      target: "7525575507"
    alerts:
      type: webhook
      target: https://hooks.example.com/alerts
  dataResources:
    backupMaxAge: "24h"
    databases:
      - kind: cnpg.io/Cluster
        namespace: backstage
        name: backstage-db
      - kind: cnpg.io/Cluster
        namespace: ideavault
        name: ideavault-db
    persistentStorage:
      - kind: PersistentVolumeClaim
        namespace: harbor
        name: harbor-registry
      - kind: PersistentVolumeClaim
        namespace: monitoring
        name: prometheus-data
    objectStorage:
      - kind: s3-bucket
        name: cnpg-backups
        provider: minio
      - kind: s3-bucket
        name: velero-backups
        provider: minio
  mcpServers:
    k8sgpt:
      endpoint: http://k8sgpt.agents:8089
      capabilities:
        - k8sgpt.analyze
